### ISSUE TITLE
RecursionError in formatter

### ISSUE THREAD

**Issue by mdefeche** [ghazi-git/drf-standardized-errors#51]
Hello,

I ran into a RecursionError when processing a large list of items with ListSerializer

I'm using drf-standardized-errors 0.12.6 and drf 3.14

You can reproduce it by calling this endpoint

```
@api_view()
@permission_classes([IsAuthenticated])
def versions(request):
    errors = [{} for i in range(1, 1000)]
    raise serializers.ValidationError(errors)
```
This will generate
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/handler.py", line 27, in exception_handler
    return exception_handler_class(exc, context).run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/handler.py", line 42, in run
    data = self.format_exception(exc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/handler.py", line 86, in format_exception
    return exception_formatter_class(exc, self.context, self.exc).run()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/formatter.py", line 39, in run
    errors = self.get_errors()
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/formatter.py", line 56, in get_errors
    return flatten_errors(self.exc.detail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/formatter.py", line 117, in flatten_errors
    return flatten_errors(first_item, new_attr, index) + flatten_errors(
                                                         ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/formatter.py", line 117, in flatten_errors
    return flatten_errors(first_item, new_attr, index) + flatten_errors(
                                                         ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/formatter.py", line 117, in flatten_errors
    return flatten_errors(first_item, new_attr, index) + flatten_errors(
                                                         ^^^^^^^^^^^^^^^
  [Previous line repeated 937 more times]
  File "/usr/local/lib/python3.11/site-packages/drf_standardized_errors/formatter.py", line 110, in flatten_errors
    first_item, *rest = detail
    ^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Thank you for the library, highly appreciated :-)

**Comment by ghazi-git** [comment]
Thank you for reporting the issue, I was able to reproduce it with your sample code. I'll try to fix it once I get some time.
